codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 60%
        threshold: 5%
        base: auto

  changes:
    default:
      layout: "reach, diff, flags, files"
      behavior: default

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  backend:
    paths:
      - backend/
    carryforward: true

  flutter:
    paths:
      - app/
    carryforward: true

  food_variety:
    paths:
      - backend/internal/features/food_variety/
      - app/lib/src/features/food_variety/
    carryforward: false

ignore:
  - "**/*_test.go"
  - "**/*.freezed.dart"
  - "**/*.g.dart"
  - "**/test/**"
  - "**/*.pb.go"
  - "**/mock_*.go"
  - "**/mocks/**"
  - "backend/cmd/**"
  - "app/lib/generated/**"

github_checks:
  annotations: true
